### ISSUE TITLE
Mod Installer won't recognize some mods

### ISSUE THREAD

**Issue by Aegarain** [WFIOST/H3VR-Mod-Installer-Database#25]
List: FTW Arms Ammo Boxes, FTW Arms Foregrips, Modern Warfighter LIghts and Lasers. 

I can install any of these mods through the mod installer without issue. But when I close and reopen it, it cannot detect them, and sets their version number to 0.0.0. The mods are still installed in the game directory, but they don't show as installed in the mod installer. I'm 90% sure this is because the delinfo for those mods in the database is different than the current filenames for those mods.

**Comment by Aegarain** [comment]
I'll just keep this open until it's resolved

**Comment by Frityet** [comment]
Known issue, being fixed soon
